In [192]:
import pandas as pd

df= pd.read_csv("datasets/urad.csv", skiprows=1)

In [193]:
df.head(10)

,State,Commodity Group,Commodity,Date,Arrival Quantity 01-01-2021 to 31-03-2026,Arrival Unit,Modal Price 01-01-2021 to 31-03-2026,Price Unit
0,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),20-04-2021,0.01,Metric Tonnes,6900.0,Rs./Quintal
1,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),14-10-2021,4.90,Metric Tonnes,6900.0,Rs./Quintal
2,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),05-11-2021,2.20,Metric Tonnes,5676.0,Rs./Quintal
3,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),06-11-2021,1.30,Metric Tonnes,5950.0,Rs./Quintal
4,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),09-11-2021,0.20,Metric Tonnes,6051.0,Rs./Quintal
5,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),11-11-2021,0.30,Metric Tonnes,6160.0,Rs./Quintal
6,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),15-11-2021,0.60,Metric Tonnes,6309.0,Rs./Quintal
7,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),22-11-2021,0.70,Metric Tonnes,6150.0,Rs./Quintal
8,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),26-11-2021,0.30,Metric Tonnes,3500.0,Rs./Quintal
9,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),01-12-2021,0.80,Metric Tonnes,5774.0,Rs./Quintal

In [194]:
df.columns = df.columns.str.strip()

In [195]:
df.rename(columns={
    "Arrival Quantity 01-01-2021 to 31-03-2026": "Arrival",
    "Modal Price 01-01-2021 to 31-03-2026": "Price"
}, inplace=True)

In [196]:
df.head()

,State,Commodity Group,Commodity,Date,Arrival,Arrival Unit,Price,Price Unit
0,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),20-04-2021,0.01,Metric Tonnes,6900.0,Rs./Quintal
1,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),14-10-2021,4.90,Metric Tonnes,6900.0,Rs./Quintal
2,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),05-11-2021,2.20,Metric Tonnes,5676.0,Rs./Quintal
3,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),06-11-2021,1.30,Metric Tonnes,5950.0,Rs./Quintal
4,Andhra Pradesh,Pulses,Black Gram(Urd Beans)(Whole),09-11-2021,0.20,Metric Tonnes,6051.0,Rs./Quintal

In [197]:
commodity_mapping = {
    "Paddy(Common)": "Rice",
    "Maize": "Maize",
    "Jowar(Sorghum)": "Jowar",
    "Bajra(Pearl Millet/Cumbu)": "Bajra",
    "Groundnut": "Groundnut",
    "Black Gram(Urd Beans)(Whole)": "Urad",
    "Green Gram(Moong)(Whole)": "Moong"
}

In [198]:
df["Commodity"] = df["Commodity"].replace(commodity_mapping)

In [199]:
df.head()

,State,Commodity Group,Commodity,Date,Arrival,Arrival Unit,Price,Price Unit
0,Andhra Pradesh,Pulses,Urad,20-04-2021,0.01,Metric Tonnes,6900.0,Rs./Quintal
1,Andhra Pradesh,Pulses,Urad,14-10-2021,4.90,Metric Tonnes,6900.0,Rs./Quintal
2,Andhra Pradesh,Pulses,Urad,05-11-2021,2.20,Metric Tonnes,5676.0,Rs./Quintal
3,Andhra Pradesh,Pulses,Urad,06-11-2021,1.30,Metric Tonnes,5950.0,Rs./Quintal
4,Andhra Pradesh,Pulses,Urad,09-11-2021,0.20,Metric Tonnes,6051.0,Rs./Quintal

In [200]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, errors='coerce')
df["Arrival"] = pd.to_numeric(df["Arrival"], errors='coerce')
df["Price"] = pd.to_numeric(df["Price"], errors='coerce')

In [201]:
df.head()

,State,Commodity Group,Commodity,Date,Arrival,Arrival Unit,Price,Price Unit
0,Andhra Pradesh,Pulses,Urad,2021-04-20,0.01,Metric Tonnes,6900.0,Rs./Quintal
1,Andhra Pradesh,Pulses,Urad,2021-10-14,4.90,Metric Tonnes,6900.0,Rs./Quintal
2,Andhra Pradesh,Pulses,Urad,2021-11-05,2.20,Metric Tonnes,5676.0,Rs./Quintal
3,Andhra Pradesh,Pulses,Urad,2021-11-06,1.30,Metric Tonnes,5950.0,Rs./Quintal
4,Andhra Pradesh,Pulses,Urad,2021-11-09,0.20,Metric Tonnes,6051.0,Rs./Quintal

In [202]:
df = df.dropna()
df = df[(df["Arrival"] > 0) & (df["Price"] > 0)]

In [203]:
df.shape[0]

17274

In [204]:
df.to_csv("urad1.csv", index=False)

In [206]:
import pandas as pd
import os

DATA_FOLDER = "."   # current directory

all_dfs = []

for file in os.listdir(DATA_FOLDER):
    if file.endswith(".csv"):   # better than "1.csv"
        path = os.path.join(DATA_FOLDER, file)
        df = pd.read_csv(path)
        all_dfs.append(df)

# Merge all
global_df = pd.concat(all_dfs, ignore_index=True)

# Save
global_df.to_csv("global_dataset.csv", index=False)

print("Merged all crops!")
print("Total rows:", global_df.shape)

Merged all crops!
Total rows: (127025, 8)